language: python

python:
  - "3.5"
  - "3.6"

install: pip install tox-travis coverage
script: tox

after_success:
  - coverage combine tests/
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
